experiment:
  min_rays: 10000
  max_rays: 1000000
  relative_standard_error_threshold: 0.1

compute:
  backend: Host_Cpu_CpuOmpBlocks
  openpmd_backend: auto
  parallel_mode: single
  num_devices: 1
  ranks_per_node: 1
